@startuml DM

skinparam classAttributeIconSize 0
hide empty attributes
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> WarehouseManagement"{
}

package "<<aggregate>> Logistics"{

}

package "<<aggregate>> Authz" {
}



@enduml