@startuml DMWarehouseManagement

skinparam classAttributeIconSize 0
hide empty attributes
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> WarehouseManagement"{
  entity Warehouse
  entity Store
  entity ChargingStation
  class WarehouseIndentifier
  class WarehouseDesignation
  class WarehouseAddress
  class WarehouseCoordinates
  class StoreName
  class StoreIndentifier 
  class CurrentOccupation
  class TotalOccupation

}

package "<<aggregate>> Logistics"{
  entity Truck 
  class Tare
  class Capacity
  class MaximumBatteryCapacity
  class Autonomy
  class FastChargeTime

}

entity Warehouse <<entity>> <<Root>>
class WarehouseIndentifier <<(V,#FF8B40) value object>>
class WarehouseDesignation <<(V,#FF8B40) value object>>
class WarehouseAddress <<(V,#FF8B40) value object>>
class WarehouseCoordinates <<(V,#FF8B40) value object>>

entity Store <<entity>>
class StoreName <<(V,#FF8B40) value object>> 
class StoreIndentifier <<(V,#FF8B40) value object>> 

entity ChargingStation <<entity>> 
class CurrentOccupation <<(V,#FF8B40) value object>> 
class TotalOccupation <<(V,#FF8B40) value object>> 

entity Truck <<entity>>
class Tare <<(V,#FF8B40) value object>>
class Capacity <<(V,#FF8B40) value object>>
class MaximumBatteryCapacity <<(V,#FF8B40) value object>>
class Autonomy <<(V,#FF8B40) value object>>
class FastChargeTime <<(V,#FF8B40) value object>>




Warehouse "1" <- "1" Store : associated with
Warehouse "1" --> "1" ChargingStation: has
ChargingStation "*" <---  "1" Truck : parks at

Warehouse "1" --> "1" WarehouseIndentifier 
Warehouse "1" --> "1" WarehouseDesignation 
Warehouse "1" --> "1" WarehouseAddress 
Warehouse "1" --> "1" WarehouseCoordinates 

Truck "1" --> "1" Tare
Truck "1" --> "1" Capacity 
Truck "1" --> "1" MaximumBatteryCapacity
Truck "1" --> "1" Autonomy
Truck "1" --> "1" FastChargeTime

Store "1" --> "1" StoreName
Store "1" --> "1" StoreIndentifier

ChargingStation "1" --> "1" CurrentOccupation
ChargingStation "1" --> "1" TotalOccupation

@enduml