@startuml
'https://plantuml.com/component-diagram
interface "WM API" as api

component "<<component>> <<container (C4)>>\nWarehouse Management\n"{

    portin 1
    package "Frameworks and Drivers Layers" {
        component "<<component>>\nWarehouseUI" as UI
        component "<<component>>\nPersistenceWarehouse" as PRT

    }

    package "Interface Adapters Layer" {
        component "<<component>>\nWarehouseController" as CT
        component "<<component>>\nWarehouseRepository" as RP

    }

    component "<<component>>\nWarehouseDTO" as DTO
    interface "WMController API" as API1
    interface "WMService API" as API2
    interface "Persistence API" as API3
    interface "Warehouse API" as API4
    interface "WM Repository API" as API5
    interface "WarehouseDTO API" as API6

    package "Application Business Rules" {
        component "<<component>>\nWarehouseService" as SV
    }

    package "Enterprise Business Rules" {
        component "<<component>>\nWarehouse" as WH

    }

}

api -- 1
UI -down..> API1 : use
CT -up- API1
SV -up-- API2
CT -down..>API2 : use

PRT -down- API3
RP -up..> API3 : use
WH -up- API4
SV -down..> API4 : use

RP -down-API5
SV -up..> API5 : use
RP -down..> API4 : use

DTO -right- API6
CT -right.> API6 : use
SV -up..> API6 : use


@enduml