@startuml LV System Context Diagram
top to bottom direction

component "<<system>>" as system{

component "<<authz>>" as authz

component "<<warehouse management>>" as whManagement

component "<<logistics>>" as logistics

component "<<planning>>" as planning

}
interface "User Interface 1" as UI1
interface "User Interface 2" as UI2
interface "User Interface 3" as UI3
interface "Google Maps API" as mapsAPI
interface "Payment API" as paymentAPI

authz -(0- UI1
authz -(0- UI2
authz -(0- UI3

whManagement -0)- authz
logistics -0)- authz
whManagement -(0- logistics
planning -0)- logistics

planning -(0- mapsAPI
logistics -(0- paymentAPI


@enduml