@startuml getPackagingSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Logistics Manager" as manager
box "<<System(C4)>>\n System"
participant UI as UI <<Container(C4)>>
participant Auth as Auth <<Container(C4)>>
participant Logistics as Logistics <<Container(C4)>>
end box

participant Google as Google <<System(C4)>>
activate manager
manager->UI: I want to login
activate UI

alt Login through email and password in EletricGo

UI -> Auth: POST Login(email, password)
activate Auth

Auth --> UI: 200 OK
deactivate Auth

else Login through Google

UI -> Google: Login with Google account
activate Google
Google --> UI: 200 OK
deactivate Google

end



UI --> manager: informs about the success of login

manager -> UI: I want to get a Packaging

UI -> manager: asks for Packaging ID

manager -> UI: inserts Packaging ID

UI -> Auth: GET getPackaging(PackagingID)
activate Auth
Auth -> Logistics: GET getPackaging(PackagingID)
activate Logistics

alt Packaging exists

Logistics --> Auth: 200 OK
Auth --> UI: 200 OK
UI --> manager: shows information about the Packaging

else Packaging doesn't exist

Logistics --> Auth: 404 NOT FOUND
Auth --> UI: 404 NOT FOUND
UI --> manager: informs that the Packaging doesn't exist

end

deactivate UI
deactivate manager
@enduml