@startuml getAllTrucksSD

autonumber
!pragma teoz true

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Fleet Manager" as manager

box "<<Container(C4)>>\n           UI" #SandyBrown
participant "FleetManagerComponent" as FleetManagerComponent <<Component(C4)>>
participant "TruckService" as TruckService <<Component(C4)>>
end box

box "<<System(C4)>>\n       System" #LightGray
participant Auth as  Auth <<Container(C4)>>
box "<<Container(C4)>>\n       Logistics" #LightCyan
participant TruckRoute as Route <<Component(C4)>>
participant TruckController as Controller <<Component(C4)>>
participant TruckService as Service <<Component(C4)>>
participant TruckRepository as Repository <<Component(C4)>>
participant Persistance as Persistance <<Component(C4)>>
end box



activate manager

manager -> FleetManagerComponent: Asks to get all Trucks
activate FleetManagerComponent
FleetManagerComponent -> TruckService: getAllTrucks()
activate TruckService
TruckService -> Auth: GET getAllTrucks()
activate Auth
Auth -> Route: GET getAllTrucks()
activate Route
Route -> Controller: GET getAllTrucks()
activate Controller



Controller -> Service: getAllTrucks()
activate Service

Service -> Repository: getAllTrucks()
activate Repository
Repository -> Persistance: find()
activate Persistance



Persistance -> Repository: AllTrucks
deactivate Persistance
Repository->Service: AllTrucks
deactivate Repository

Service -> Controller: AllTrucks
deactivate Service
Controller->Route: 200 OK + AllTrucks
deactivate Controller
Route->Auth: 200 OK + AllTrucks
deactivate Route


Auth->TruckService: 200 OK + AllTrucks
deactivate Auth
TruckService->FleetManagerComponent: 200 OK + AllTrucks
deactivate TruckService
FleetManagerComponent->manager: Shows all Trucks
deactivate FleetManagerComponent
deactivate manager





@enduml