@startuml getTruckSSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Fleet Manager" as manager
participant System as system <<System(C4)>>


manager -> system: I want to get a truck
activate system

system --> manager: asks for truck ID
deactivate system

manager -> system: inserts truck ID
activate system

alt truck exists

system --> manager: shows information about truck

else truck doesn't exist

system --> manager: informs truck doesn't exist
deactivate system

end

deactivate manager

@enduml