version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0
  windows: circleci/windows@2.2.0

jobs:
  runTests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: WarehouseManagement
          name: API Build
          command: |
            dotnet build
      - run:
          working_directory: WarehouseManagementTest
          name: API Test Solution Build
          command: |
            dotnet build
            dotnet test
      - run:
          working_directory: WarehouseManagementTest
          name: API Test Solution Run
          command: |
            dotnet test
workflows:
  buildAndTestApp:
    jobs:
      - runTests
  