version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.0
  windows: circleci/windows@2.2.0
build-and-test-WarehouseManagement:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: WarehouseManagement/
          name: Build
          command: |
            dotnet build
workflows:
  build-and-deploy:
    jobs:
      - build