@startuml deleteTruckSD

autonumber
!pragma teoz true

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Fleet Manager" as manager

box "<<System(C4)>>\n       System" #LightGray
participant SPA as  SPA <<Container(C4)>>
box "<<Container(C4)>>\n       Logistics" #LightCyan
participant TruckRoute as Route <<Component(C4)>>
participant TruckController as Controller <<Component(C4)>>
participant TruckService as Service <<Component(C4)>>
participant TruckRepository as Repository <<Component(C4)>>
participant Persistance as Persistance <<Component(C4)>>
end box



activate manager
activate SPA
manager -> SPA: Asks to delete Truck

SPA -> manager: Asks for Truck ID
deactivate SPA

manager ->SPA: Inserts Truck ID
activate SPA

SPA -> Route: DELETE deleteTruck(truckID)
activate Route
Route -> Controller :DELETE deleteTruck(truckID)
activate Controller



Controller -> Service: deleteTruck(truckInfo)
activate Service

Service -> Repository: getTruckById(TruckInfo.id)
activate Repository
Repository -> Persistance: findOne(TruckInfo.id)
activate Persistance

alt Truck exists

Persistance -> Repository: truckInfo
Repository->Service: truckInfo

Service -> Repository: delete(truckID)
Repository -> Persistance:deleteOne(truckInfo)

Persistance->Repository: true
Repository->Service: TruckInfo
Service->Controller: TruckInfo
Controller->Route: 200 OK + TruckInfo
Route->SPA: 200 OK truckInfo

SPA->manager: Informs truck was successfully deleted
deactivate Repository

else Truck doesn't exist

Service -> Repository: getTruckById(TruckInfo.id)
activate Repository
Repository -> Persistance: findOne(TruckInfo.id)

Persistance->Repository: null
Repository->Service: null
Service->Controller: error, Truck doesn't exist
Controller->Route: 404 NOT FOUND, Truck doesn't exist
Route->SPA: 404 NOT FOUND, Truck doesn't exist
SPA->manager: Informs about deletion failure


@enduml