
@startuml 
autonumber

actor "Warehouse Manager" as admin


box "<<System(C4)>>\n       EletricGo" #LightYellow
participant SPA as ui <<Container(C4)>>
box "<<Container(C4)>>\n    Warehouse Management" #LightGreen
participant WarehouseRoute as  WM <<Component(C4)>>
participant WarehouseController as  CTL <<Component(C4)>>
participant WarehouseService as  SV <<Component(C4)>>
participant "warehouse : Warehouse" as  W <<Component(C4)>>
participant "warehouseDto : WarehouseDTO" as  DTO <<Component(C4)>>
participant WarehouseRepository as  WR <<Component(C4)>>
end box
end box

admin -> ui: I want to create a new warehouse
activate ui

ui -> admin: asks for the details on the new warehouse
deactivate ui

admin -> ui: inserts the information about the new warehouse

activate ui
ui -> WM: POST CreateWarehouse(warehouseDto)
activate WM
alt If warehouse don´t exist in the system 
WM -> CTL: POST CreateWarehouse(warehouseDto)
activate CTL
CTL -> SV : CreateWarehouse(warehouseDto)
activate SV

SV -> W : Create(warehouseDto)
activate W
W --> SV : warehouse 
deactivate W

SV -> WR : save(warehouse)
activate WR
WR --> SV : true 
deactivate WR

SV -> W : toWarehouseDTO()
activate W
W --> SV : warehouseDto
deactivate W
SV --> CTL : warehouseDto
deactivate SV
CTL --> WM : warehouseDto
deactivate CTL


WM --> ui: 200 OK
deactivate WM

ui -> admin: informs about the success of the operation
deactivate ui

else If a warehouse already exists with the id entered

WM -> CTL: POST CreateWarehouse(warehouseDto)
activate WM
activate CTL
CTL -> SV : CreateWarehouse(warehouseDto)
activate SV

SV -> W : Create(warehouseDto)
activate W
W --> SV : warehouse 
deactivate W

SV -> WR : save(warehouse)
activate WR
WR --> SV : false
deactivate WR
SV --> CTL : InvalidOperationException
deactivate SV
CTL --> WM : InvalidOperationException
deactivate CTL

WM --> ui: 409 CONFLICT
deactivate WM

activate ui
ui -> admin: informs about the fail of the operation
deactivate ui 

else If the attributes do not respect the business rules
WM -> CTL: POST CreateWarehouse(warehouseDto)
activate WM
activate CTL
CTL -> SV : CreateWarehouse(warehouseDto)
activate SV

SV -> W : Create(warehouseDto)
activate W
W --> SV : BusinessRuleValidationException
deactivate W

SV --> CTL : BusinessRuleValidationException
deactivate SV
CTL --> WM : BusinessRuleValidationException
deactivate CTL

WM --> ui: 409 CONFLICT
deactivate WM

activate ui
ui -> admin: informs about the fail of the operation
deactivate ui 
end 
deactivate ui
deactivate admin

@enduml
