@startuml
autonumber

actor "Warehouse Manager" as admin


box "<<System(C4)>>\n          UI" #LightYellow
participant DeleteWarehouseComponent as uiComponent <<Container(C4)>>
participant DeleteWarehouseService as uiService <<Container(C4)>>
box "<<Container(C4)>>\n           Auth" #LightBlue
participant WarehouseController as authController <<Container(C4)>>
box "     <<Container(C4)>>\nWarehouse Management" #LightGreen
participant WarehouseRoute as  WM <<Component(C4)>>
participant WarehouseController as  CTL <<Component(C4)>>
participant WarehouseService as  SV <<Component(C4)>>
participant "warehouse : Warehouse" as  W <<Component(C4)>>
participant "warehouseDto : WarehouseDTO" as  DTO <<Component(C4)>>
participant WarehouseRepository as  WR <<Component(C4)>>
end box
end box 
admin -> uiComponent: I want to delete a warehouse
activate uiComponent

uiComponent --> admin: asks for the ID of the warehouse
deactivate uiComponent

admin -> uiComponent: inserts the ID of the warehouse
activate uiComponent

uiComponent --> admin: asks for the confirmation of the deletion
deactivate uiComponent


admin -> uiComponent: confirms the deletion
activate uiComponent

uiComponent -> uiService : deleteWarehouse(id)
activate uiService
uiService -> WM : deleteWarehouse(id)
activate WM 
WM -> CTL : DELETE Delete(id)
activate CTL
CTL -> SV : DeleteWarehouse(id)
activate SV 
deactivate WM
deactivate uiService

alt If there is a warehouse in the system with the id entered


SV -> WR : GetById(id)
activate WR 
WR --> SV : warehouse
deactivate WR
SV -> WR : Delete(warehouse)
activate WR

WR --> SV : true 
deactivate WR

SV -> W : toWarehouseDto()
activate W
W--> SV : warehouseDto
deactivate W
SV --> CTL : warehouseDto
deactivate SV
CTL --> WM : warehouseDto
activate WM
deactivate CTL
WM --> authController : warehouseDto
activate authController
authController --> uiService : warehouseDto
activate uiService
uiService --> uiComponent : 200 OK
deactivate uiService
deactivate authController 
deactivate WM
uiComponent --> admin: informs about the successful deletion
deactivate uiComponent

else If there is no warehouse in the system with the id entered

activate SV 
SV -> WR : GetById(id)
activate WR 
WR --> SV : null
deactivate WR

SV --> CTL : null
activate CTL
deactivate SV
CTL --> WM : null
activate WM
WM -> authController : null
activate authController

authController --> uiService : null 
activate uiService
uiService --> uiComponent : 404 NOT FOUND
deactivate uiService
deactivate authController
deactivate WM
deactivate CTL

activate uiComponent

uiComponent --> admin : informs about the fail of the operation

deactivate uiComponent


end 

deactivate admin
@enduml