@startuml 
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Warehouse Manager" as admin
box "<<EletricGo(C4)>>\n       System"
participant SPA as system <<Container(C4)>>
participant WarehouseManagement as  WM <<Container(C4)>>
end box
admin -> system: I want to delete a warehouse
activate system

system --> admin: asks for the ID of the warehouse
deactivate system

admin -> system: inserts the ID of the warehouse
activate system

system --> admin: asks for the confirmation of the deletion
deactivate system

admin -> system: confirms the deletion
activate system

system -> WM : DELETE DeleteWarehouse(id)
alt If there is a warehouse in the system with the id entered

activate WM

WM --> system : 200 OK 
deactivate WM
system --> admin: informs about the successful deletion
deactivate system

else If there is no warehouse in the system with the id entered

activate WM
WM --> system : 404 NOT FOUND 
deactivate WM
activate system

system --> admin : informs about the fail of the operation

deactivate system


end 

deactivate admin

@enduml