@startuml
'https://plantuml.com/component-diagram
interface "WM API" as api

component "<<component>> <<container (C4)>>\nWarehouse Management\n"{

    portin 1
    package "Frameworks and Drivers Layers" {
        component "<<component>>\nWarehouseRoute" as UI
        component "<<component>>\nPersistence" as PRT

    }

    package "Interface Adapters Layer" {
        component "<<component>>\nWarehouseController" as CT
        component "<<component>>\nWarehouseRepository" as RP

    }

    component "<<component>>\nWarehouseDTO" as DTO
    component "<<component>>\nWarehouseEntityTypeConfiguration" as SCHEMA
    interface "IControllerBase" as API1
    interface "IWarehouseService" as API2
    interface "IWarehousePersistence" as API3
    interface "IEntity" as API4
    interface "IWarehouseRepository" as API5
    interface "IWarehouseDTO" as API6
    interface "IEntityTypeConfiguration" as API7

    package "Application Business Rules" {
        component "<<component>>\nWarehouseService" as SV
    }

    package "Enterprise Business Rules" {
        component "<<component>>\nWarehouse" as WH

    }

}

api -- 1
UI -down..> API1 : use
CT -up- API1
SV -up-- API2
CT -down..>API2 : use

PRT -down- API3
RP -up..> API3 : use
WH -up- API4
SV -down..> API4 : use

RP -down-API5
SV -up..> API5 : use
RP -down..> API4 : use

DTO -left- API6
CT -right.> API6 : use
SV -up..> API6 : use

SCHEMA -- API7
RP -up...> API7 : use

PRT ..> API7 : use

@enduml