@startuml
autonumber

actor "Warehouse Manager" as admin 

box "<<Container(C4)>>\n       UI" #LightYellow
participant CreateWarehouseComponent as uiComponent <<Container(C4)>>
participant CreateWarehouseService as uiService <<Container(C4)>>
box "<<Container(C4)>>\n       Auth" #LightBlue
participant WarehouseController as authController <<Container(C4)>>
box "<<Container(C4)>>\n    Warehouse Management" #LightGreen
participant WarehouseRoute as  WM <<Component(C4)>>
participant WarehouseController as  CTL <<Component(C4)>>
participant WarehouseService as  SV <<Component(C4)>>
participant "warehouse : Warehouse" as  W <<Component(C4)>>
participant "warehouseDto : WarehouseDTO" as  DTO <<Component(C4)>>
participant WarehouseRepository as  WR <<Component(C4)>>
end box
end box


admin -> uiComponent: I want to consult the warehouses in the system
activate uiComponent

uiComponent -> uiService : getAllWarehouses()
activate uiService
deactivate uiComponent
uiService -> authController : GET getAllWarehouse()
activate authController
authController -> WM : GET GetAll()
activate WM

WM -> CTL : GetAll()
deactivate WM
activate CTL
CTL -> SV : GetWarehouses()

deactivate authController
deactivate uiService
alt if there are warehouses in the system


activate SV 
SV -> WR : GetAll()
activate WR
WR --> SV : listOfWarehouses
deactivate WR
SV -> W : toWarehouseDto(listOfWarehouse)
activate W

W --> SV : listOfWarehousesDto
deactivate W
SV --> CTL : listOfWarehousesDto
deactivate SV
CTL --> WM : listOfWarehousesDto
activate WM
deactivate CTL
WM --> authController : 200 OK
activate authController
authController --> uiService : 200 OK
activate uiService
uiService --> uiComponent : 200 OK
activate uiComponent

deactivate uiService

deactivate authController 
deactivate WM

uiComponent --> admin: show all warehouses in the system
deactivate uiComponent

else If there are no warehouses in the system



activate SV 
SV -> WR : GetAll()

WR --> SV : null

SV --> CTL : null
activate CTL
deactivate SV
CTL --> WM : null
activate WM


deactivate CTL
WM --> authController : 404 NOT FOUND
deactivate WM
activate authController
authController --> uiService : 404 NOT FOUND
deactivate authController
activate uiService
uiService --> uiComponent : 404 NOT FOUND
deactivate uiService

activate uiComponent
 
uiComponent --> admin: show message error "Warehouses not found"
deactivate uiComponent 


end

deactivate admin
@enduml