@startuml getAllPackagingSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}


actor "Logistics Manager" as manager
box "<<System(C4)>>\n       System"
participant SPA as  SPA <<Container(C4)>>
participant Logistics as  Logistics <<Container(C4)>>
end box


manager -> SPA: I want to get all Packagings
activate SPA

SPA -> Logistics: GET getAllPackaging(PackagingID)
activate Logistics

Logistics -> SPA: 200 OK

SPA -> manager: all Packagings



deactivate Logistics
deactivate SPA
deactivate manager


@enduml