@startuml Level 2 - Physical View

left to right direction
frame "EletricGo" {

    node "UI Server localhost:4200" as s1 {
        
        component "UI"
    }

    node "Auth Server localhost:3001" as s2 {

    component "AUTH"
    }
    
    
    node "Logistics Server localhost:3000" as s3 {
    component "Logistics"
    }

    node "WarehouseManagement Server localhost:5000/5001" as s4 {
    component "Warehouse Management"
    }
    
    node "Planning Server localhost:3002" as s5 {
    component "Planning"
    }
}

@enduml
