
@startuml
component "<<component>>\n<<Context(C4)>>\nEletricGo" as c2 {
  component "<<component>>\n<<Container(C4)>>\n User Interface" as UI{
        portin 3
  }
  component "<<component>>\n<<Container(C4)>>\n WarehouseManagement" as WMNG
  component "<<component>>\n<<Container(C4)>>\n Logistics" as LG
  component "<<component>>\n<<Container(C4)>>\n Planning" as PL
  portin 1
  portout 2

}

interface UICliente as CL
interface UIAdministrator as ADM
interface UIWarehouseManager as MNG
interface UIFleetManager as FMNG
interface UILogisticsManager as LMNG

CL --- 1
ADM --- 1
MNG --- 1
FMNG --- 1
LMNG --- 1

2 -(0- SSOAPI

3--1

UI -(0- WMNG : "" WM API ""
UI -(0- LG: "" LOG API ""
PL -(0- LG : "" LOG API ""
LG -(0- PL : "" PLN API ""
PL -(0- WMNG : "" WM API ""
LG -(0- WMNG : "" WM API ""

@enduml
