
@startuml Level 2 - Logic View
component "<<component>>\n<<Context(C4)>>\nEletricGo" as c2 {
  component "<<component>>\n<<Container(C4)>>\n User Interface" as UI{
        portin 3
  }
  component "<<component>>\n<<Container(C4)>>\n Authentication" as AUTH
  component "<<component>>\n<<Container(C4)>>\n WarehouseManagement" as WMNG
  component "<<component>>\n<<Container(C4)>>\n Logistics" as LG
  component "<<component>>\n<<Container(C4)>>\n Planning" as PL
  interface "Auth API" as AUTHAPI
  interface "WM API" as WMAPI
  interface "LOG API" as LOGAPI
  interface "PLN API" as PLNAPI
  portin 1
  portout 2

}

interface UIAdministrator as ADM
interface UIWarehouseManager as MNG
interface UIFleetManager as FMNG
interface UILogisticsManager as LMNG

ADM --- 1
MNG --- 1
FMNG --- 1
LMNG --- 1

2 -(0- SSOAPI

3--1

AUTHAPI -- AUTH
LG -- LOGAPI
WMNG --- WMAPI
UI ..> AUTHAPI
PL ..> AUTHAPI
LG ...> WMAPI
PL --- PLNAPI


AUTH ...> LOGAPI
AUTH ...> PLNAPI
AUTH ...> WMAPI


@enduml
