@startuml updateTruckSD
autonumber
!pragma teoz true
skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Fleet Manager" as manager


box "<<System(C4)>>\n       System" #Gold
participant SPA as  SPA <<Container(C4)>>
box "<<Container(C4)>>\n       Logistics" #LightBlue
participant TruckRoute as Route <<Component(C4)>>
participant TruckController as Controller <<Component(C4)>>
participant TruckService as Service <<Component(C4)>>
participant TruckRepository as Repository <<Component(C4)>>
participant Persistence as Persistence <<Component(C4)>>
end box
end box

manager -> SPA: I want to update a truck
activate SPA

SPA --> manager: asks for truck ID and new truck info
deactivate SPA

manager -> SPA: inserts truck ID and new truck info
activate SPA

SPA -> Route: PUT updateTruck(truck)
activate Route

Route -> Controller: PUT updateTruck(truck)
activate Controller

Controller -> Service: updateTruck(truckInfo)

Service -> Repository: getTruckById(truckInfo.id)

Repository -> Persistence: findOne(truckInfo.id)

alt truck already exists

Persistence --> Repository: truck

Repository --> Service: truck

Service -> Repository: update(truckInfo)

Repository -> Persistence: save(truckInfo)

Persistence --> Repository: true

Repository --> Service: truckInfo

Service --> Controller: truckInfo

Controller --> Route: 200 OK + truckInfo

Route --> SPA: 200 OK + truckInfo
SPA --> manager: shows updated information


else truck doesn't exist

Persistence --> Repository: null

Repository --> Service: null

Service --> Controller: error, Truck doesn't exist

Controller --> Route: 404 NOT FOUND, Truck doesn't exist

Route --> SPA: 404 NOT FOUND, Truck doesn't exist
deactivate Route
SPA --> manager: informs about the failure of the update

end

deactivate SPA
deactivate manager

@enduml