@startuml LV System Context Diagram

component "<<system>>" as system

interface "Google Maps API" as mapsAPI
interface "User Interface 1" as UI1
interface "User Interface 2" as UI2
interface "User Interface 3" as UI3
interface "Payment API" as paymentAPI

system -(0- mapsAPI
UI1 -0- system
UI2 -0- system
UI3 -0- system
system -(0- paymentAPI


@enduml