@startuml

left to right direction
actor "Administrator" as ADM
actor "Warehouse Manager" as MNG
actor "Fleet Manager" as FMNG
actor "Logistics Manager" as LMNG

rectangle EletricGo {

    usecase "Create a Warehouse" as UC1
    usecase "Reade information about a Warehouse" as UC2
    usecase "Update information about a Warehouse " as UC3
    usecase "Delete a Warehouse" as UC4
    usecase "List the Warehouses" as UC5

    usecase "Create a Delivery" as UC6
    usecase "Reade information about a Delivery" as UC7
    usecase "Update information about Delivery " as UC8
    usecase "Delete a Delivery" as UC9
    usecase "List the Deliveries" as UC10

    usecase "Create a Truck" as UC11
    usecase "Reade information about a Truck" as UC12
    usecase "Update information about Truck" as UC13
    usecase "Delete a Truck" as UC14
    usecase "List the Trucks" as UC15

    usecase "Create a Path" as UC16
    usecase "Reade information about a Path" as UC17
    usecase "Update information about Path" as UC18
    usecase "Delete a Path" as UC19
    usecase "List the Paths" as UC20

    usecase "Create a Client" as UC21
    usecase "Reade information about a Client" as UC22
    usecase "Update information about Client" as UC23
    usecase "Delete a Client" as UC24
    usecase "List the Clients" as UC25
    
    usecase "Create a packaging" as UC26
    usecase "Reade information about a packaging" as UC27
    usecase "Update information about packaging" as UC28
    usecase "Delete a packaging" as UC29
    usecase "List the packaging" as UC30
    
    usecase "Create a trip" as UC31
    usecase "Reade information about a trip" as UC32
    usecase "Update information about a trip" as UC33
    usecase "Delete a trip" as UC34
    usecase "List the trips" as UC35


}


MNG --> UC1
MNG --> UC2
MNG --> UC3
MNG --> UC4
MNG --> UC5

MNG --> UC6
MNG --> UC7
MNG --> UC8
MNG --> UC9
MNG --> UC10

FMNG --> UC11
FMNG --> UC12
FMNG --> UC13
FMNG --> UC14
FMNG --> UC15

LMNG --> UC16
LMNG --> UC17
LMNG --> UC18
LMNG --> UC19
LMNG --> UC20

LMNG --> UC26
LMNG --> UC27
LMNG --> UC28
LMNG --> UC29
LMNG --> UC30

LMNG --> UC31
LMNG --> UC32
LMNG --> UC33
LMNG --> UC34
LMNG --> UC35

ADM --> UC21
ADM --> UC22
ADM --> UC23
ADM --> UC24
ADM --> UC25


@enduml
