@startuml scenarioView

skinparam actorStyle awesome
"Warehouse Manager" as Admin

"Create Delivery" as (US1)
"Read Delivery" as (US2)
"Update Delivery" as (US2)
"Delete Warehouses" as (US4)

Admin --> (US1)
Admin --> (US2)
Admin --> (US3)
Admin --> (US4)

@enduml