@startuml createPathSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Logistics Manager" as manager
box "<<System(C4)>>\n System"
participant UI as UI <<Container(C4)>>
participant Auth as Auth <<Container(C4)>>
participant Logistics as Logistics <<Container(C4)>>
participant WarehouseManagement as WarehouseManagement << Container(C4)>>
end box

participant Google as Google <<System(C4)>>


activate manager
manager->UI: I want to login
activate UI

alt Login through email and password in EletricGo

UI -> Auth: POST Login(email, password)
activate Auth

Auth --> UI: 200 OK
deactivate Auth

else Login through Google

UI -> Google: Login with Google account
activate Google
Google --> UI: 200 OK
deactivate Google

end



UI --> manager: informs about the success of login

manager -> UI: I want to create a new path

UI --> manager: asks for the details on the new path

manager -> UI: inserts the information about the new path

UI -> Auth: POST createPath(pathInfo)
activate Auth
Auth -> Logistics: POST createPath(pathInfo)
activate Logistics
Logistics -> WarehouseManagement: Confirms warehouses existence(warehouseInfo)
activate WarehouseManagement

alt path doesn't exist and warehouse does
WarehouseManagement --> Logistics: 200 OK
Logistics --> Auth: 201 Created
Auth --> UI: 201 Created
UI --> manager: informs about the success of the creation

else path already exists and warehouse does
WarehouseManagement --> Logistics: 200 OK
Logistics --> Auth: 409 Conflict
Auth --> UI: 409 Conflict
UI --> manager: informs about the failure of the creation

else path already exists and warehouse doesn't
WarehouseManagement --> Logistics: 404 Not found
Logistics --> Auth: 404 Not found
Auth --> UI: 404 Not found

else path doesn't exist nor warehouse
WarehouseManagement --> Logistics: 404 Not found
Logistics --> Auth: 404 Not found
Auth --> UI: 404 Not found

UI --> manager: Informs warehouse doesn't exist.

end

deactivate UI
deactivate manager
@enduml