name: WarehouseManagement API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  BuildAndTestAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          
      - name: Restore dependencies
        working-directory: ./WarehouseManagement
        run: dotnet restore
      - name: Build
        working-directory: ./WarehouseManagement
        run: dotnet build --no-restore
      - name: Test
        working-directory: ./WarehouseManagementTest
        run: dotnet test --no-restore --verbosity normal
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "./coverage/base-lcov.info"
          send-summary-comment: true
          show-annotations: "warning"