name: WarehouseManagement API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          
      - name: Restore dependencies
        working_directory: WarehouseManagement
        run: dotnet restore
      - name: Build
        working_directory: WarehouseManagement
        run: dotnet build --no-restore
      - name: Test
        working_directory: WarehouseManagementTest
        run: dotnet test --no-restore --verbosity normal