name: Angular Testing and Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    AZURE_WEBAPP_NAME: EletricGo57
    NODE_PATH: './UI'
    CACHE_PATH: './UI/package-lock.json'
    NODE_VERSION: '16.17.1'

jobs:
  BuildAndTestUI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.NODE_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.CACHE_PATH }}
      
      - name: npm install, build, and test
        run: |
          npm prune --production
          npm install
          npm install -g @angular/cli@latest
          npm run build --if-present
<<<<<<< HEAD
=======
          ng build
>>>>>>> parent of 5bfa857 (Revert "final test")

  Deployment:
    runs-on: ubuntu-latest
    needs: BuildAndTestUI
    environment:
      name: 'production'
      url: ${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net
    
    steps:
<<<<<<< HEAD
=======
      - uses: actions/checkout@v2
>>>>>>> parent of 5bfa857 (Revert "final test")
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_UI_PUBLISH_PROFILE }}
          package: './UI/dist/spa'
