name: Angular Testing and Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    AZURE_WEBAPP_NAME: EletricGo57
    NODE_PATH: './UI'
    CACHE_PATH: './UI/package-lock.json'
    NODE_VERSION: '16.17.1'

jobs:
  BuildAndTestUI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.NODE_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.CACHE_PATH }}
      
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
      
      - run: |
          zip -r node-app.zip node_modules
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: './UI/node-app.zip'

  Deployment:
    runs-on: ubuntu-latest
    needs: BuildAndTestUI
    environment:
      name: 'production'
      url: ${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - run: |
          unzip node-app.zip
          rm node-app.zip

      - uses: actions/checkout@v2
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_UI_PUBLISH_PROFILE }}
          package: ${{ env.NODE_PATH }}