name: Logistics Testing and Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    AZURE_WEBAPP_NAME: Logistics57
    NODE_PATH: './Logistics'
    CACHE_PATH: './Logistics/package-lock.json'
    NODE_VERSION: '16.17.1'

jobs:
  BuildAndTestLogisticsAPI:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.NODE_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.CACHE_PATH }}

      - name: Clean Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
      
  Deployment:
    runs-on: ubuntu-latest
    needs: [BuildAndTestLogisticsAPI]
    environment:
      name: 'production'
      url: ${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net

    defaults:
      run:
        working-directory: ${{ env.NODE_PATH }}
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_NODE_PUBLISH_PROFILE }}
          package: '.'
