name: Logistics Testing and Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    AZURE_WEBAPP_NAME: Logstics57
    NODE_PATH: './Logistics'
    NODE_VERSION: '18.0.0'

jobs:
  BuildAndTestLogisticsAPI:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.NODE_PATH }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
      
  Deployment:
    runs-on: ubuntu-latest
    needs: [BuildAndTestLogisticsAPI]
    environment:
      name: 'production'
      url: ${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net

    defaults:
      run:
        working-directory: ${{ env.NODE_PATH }}
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_NODE_PUBLISH_PROFILE }}
          package: '.'