name: EletricGoSoftware

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    DOTNET_PATH: './WarehouseManagement'
    NODE_PATH: './Logistics'

jobs:
  BuildAndTestWarehouseAPI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DOTNET_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Code Coverage Calculation
        run: dotnet dotnet test --collect:"XPlat Code Coverage"
  
  BuildAndTestLogisticsAPI:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.NODE_PATH }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test